# Generated by Django 2.1.2 on 2018-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_image',
            field=models.FileField(blank='true', null='true', upload_to='vimages'),
            preserve_default='true',
        ),
    ]
