# Generated by Django 2.1.2 on 2018-10-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0002_video_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('no_of_channels', models.IntegerField()),
            ],
        ),
    ]
