# Generated by Django 2.1.2 on 2018-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='email_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.FileField(blank='true', null='true', upload_to='vimages/'),
        ),
    ]
