# Generated by Django 2.1.2 on 2018-10-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0004_auto_20181027_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_videos', models.IntegerField()),
                ('channel_name', models.CharField(max_length=40)),
                ('channel_subscribers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='', max_length=100)),
                ('video_thumbnail', models.FileField(blank='true', default='', null='true', upload_to='vimages')),
                ('video_description', models.TextField(blank='true', default='', null='true')),
                ('video_upload', models.FileField(blank='true', default='', null='true', upload_to='videos')),
                ('video_category', models.CharField(default='', max_length=40)),
                ('video_date', models.DateTimeField(auto_now_add=True)),
                ('video_views', models.IntegerField(default=0)),
                ('video_duration', models.TimeField()),
                ('video_likes', models.IntegerField(default=0)),
                ('video_dislikes', models.IntegerField(default=0)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosharing1.Channel')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_of_channels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosharing1.User'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosharing1.User'),
        ),
        migrations.AddField(
            model_name='comments',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosharing1.Videos'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosharing1.User'),
        ),
    ]
