# Generated by Django 2.1.2 on 2018-10-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0005_auto_20181027_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
