# Generated by Django 2.1.2 on 2018-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0006_auto_20181029_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('video_name', models.CharField(max_length=50)),
                ('video_description', models.TextField()),
                ('comment_enable', models.BooleanField()),
                ('category', models.CharField(choices=[('E', 'Education'), ('p', 'politics'), ('E1', 'entertainment'), ('S', 'sports'), ('O', 'other')], default='', max_length=2)),
            ],
        ),
    ]
