# Generated by Django 2.1.2 on 2018-11-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0007_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='videos',
            name='category',
            field=models.CharField(choices=[('E', 'Education'), ('p', 'politics'), ('E1', 'entertainment'), ('S', 'sports'), ('O', 'other')], default='', max_length=2),
        ),
    ]
