# Generated by Django 2.1.2 on 2018-11-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0009_auto_20181105_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_discription',
            new_name='channel_description',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='instragram_link',
            new_name='instagram_link',
        ),
    ]
