# Generated by Django 2.1.2 on 2018-11-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0010_auto_20181105_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='channel_id',
        ),
    ]
