# Generated by Django 2.1.2 on 2018-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0011_auto_20181112_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_videos',
            field=models.IntegerField(default=0),
        ),
    ]
