# Generated by Django 2.1.2 on 2018-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0012_auto_20181112_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
