# Generated by Django 2.1.5 on 2019-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosharing1', '0013_auto_20181112_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0, unique=True)),
                ('movie_name', models.CharField(default='', max_length=100)),
                ('movie_genre', models.CharField(default='', max_length=100)),
                ('movie_img', models.FileField(blank='true', default='', null='true', upload_to='vimages')),
                ('movie_link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
